#ifdef HAVE_CURLINFO_EFFECTIVE_URL
CURLINFO(EFFECTIVE_URL),
#endif
#ifdef HAVE_CURLINFO_RESPONSE_CODE
CURLINFO(RESPONSE_CODE),
#endif
#ifdef HAVE_CURLINFO_TOTAL_TIME
CURLINFO(TOTAL_TIME),
#endif
#ifdef HAVE_CURLINFO_NAMELOOKUP_TIME
CURLINFO(NAMELOOKUP_TIME),
#endif
#ifdef HAVE_CURLINFO_CONNECT_TIME
CURLINFO(CONNECT_TIME),
#endif
#ifdef HAVE_CURLINFO_PRETRANSFER_TIME
CURLINFO(PRETRANSFER_TIME),
#endif
#ifdef HAVE_CURLINFO_SIZE_UPLOAD
CURLINFO(SIZE_UPLOAD),
#endif
#ifdef HAVE_CURLINFO_SIZE_DOWNLOAD
CURLINFO(SIZE_DOWNLOAD),
#endif
#ifdef HAVE_CURLINFO_SPEED_DOWNLOAD
CURLINFO(SPEED_DOWNLOAD),
#endif
#ifdef HAVE_CURLINFO_SPEED_UPLOAD
CURLINFO(SPEED_UPLOAD),
#endif
#ifdef HAVE_CURLINFO_HEADER_SIZE
CURLINFO(HEADER_SIZE),
#endif
#ifdef HAVE_CURLINFO_REQUEST_SIZE
CURLINFO(REQUEST_SIZE),
#endif
#ifdef HAVE_CURLINFO_SSL_VERIFYRESULT
CURLINFO(SSL_VERIFYRESULT),
#endif
#ifdef HAVE_CURLINFO_FILETIME
CURLINFO(FILETIME),
#endif
#ifdef HAVE_CURLINFO_CONTENT_LENGTH_DOWNLOAD
CURLINFO(CONTENT_LENGTH_DOWNLOAD),
#endif
#ifdef HAVE_CURLINFO_CONTENT_LENGTH_UPLOAD
CURLINFO(CONTENT_LENGTH_UPLOAD),
#endif
#ifdef HAVE_CURLINFO_STARTTRANSFER_TIME
CURLINFO(STARTTRANSFER_TIME),
#endif
#ifdef HAVE_CURLINFO_CONTENT_TYPE
CURLINFO(CONTENT_TYPE),
#endif
#ifdef HAVE_CURLINFO_REDIRECT_TIME
CURLINFO(REDIRECT_TIME),
#endif
#ifdef HAVE_CURLINFO_REDIRECT_COUNT
CURLINFO(REDIRECT_COUNT),
#endif
#ifdef HAVE_CURLINFO_PRIVATE
CURLINFO(PRIVATE),
#endif
#ifdef HAVE_CURLINFO_HTTP_CONNECTCODE
CURLINFO(HTTP_CONNECTCODE),
#endif
#ifdef HAVE_CURLINFO_HTTPAUTH_AVAIL
CURLINFO(HTTPAUTH_AVAIL),
#endif
#ifdef HAVE_CURLINFO_PROXYAUTH_AVAIL
CURLINFO(PROXYAUTH_AVAIL),
#endif
#ifdef HAVE_CURLINFO_OS_ERRNO
CURLINFO(OS_ERRNO),
#endif
#ifdef HAVE_CURLINFO_NUM_CONNECTS
CURLINFO(NUM_CONNECTS),
#endif
#ifdef HAVE_CURLINFO_SSL_ENGINES
CURLINFO(SSL_ENGINES),
#endif
#ifdef HAVE_CURLINFO_COOKIELIST
CURLINFO(COOKIELIST),
#endif
#ifdef HAVE_CURLINFO_LASTSOCKET
CURLINFO(LASTSOCKET),
#endif
#ifdef HAVE_CURLINFO_FTP_ENTRY_PATH
CURLINFO(FTP_ENTRY_PATH),
#endif
#ifdef HAVE_CURLINFO_REDIRECT_URL
CURLINFO(REDIRECT_URL),
#endif
#ifdef HAVE_CURLINFO_PRIMARY_IP
CURLINFO(PRIMARY_IP),
#endif
#ifdef HAVE_CURLINFO_APPCONNECT_TIME
CURLINFO(APPCONNECT_TIME),
#endif
#ifdef HAVE_CURLINFO_CERTINFO
CURLINFO(CERTINFO),
#endif
#ifdef HAVE_CURLINFO_CONDITION_UNMET
CURLINFO(CONDITION_UNMET)
#endif
